executors:
  node:
    docker:
      - image: circleci/node:erbium

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}

  install_node_modules: &install_node_modules
    run:
      name: Install NPM dependencies
      command: npm install

  save_cache: &save_cache
    save_cache:
      name: Save NPM package cache
      key: v{{ .Environment.versionCache }}-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      paths:
        - ./node_modules

version: 2.1

jobs:
  install:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
  build_and_lint:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Build Public
          command: npm run generate
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: install netlify cli
          command: sudo npm install -g --unsafe-perm --silent netlify-cli
      - run:
          name: deploy site to netlify
          command: |
            netlify deploy --dir=./dist -p | awk '/Website Draft URL: /{print}' > my_workspace/echo-output
      - persist_to_workspace:
        root: my_workspace
        paths:
          - echo-output
  print:
    executor: node
    steps:
      - run:
          name: deploy site to netlify
          command: echo $(cat my_workspace/echo-output)
      - attach_to_workspace:
        at: my_workspace

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - build_and_lint:
          requires:
            - install
      - deploy:
          context: NuxtNetlify
          requires:
            - build_and_lint
